### ISSUE TITLE
cargo test fails

### ISSUE THREAD

**Issue by vidhyasasi** [ken-matsui/uuid-v4-cli#34]
Installed the uuid-v4-cli 0.3.0 from the soiurce and ran cargo test, resulted in the following fails:
failures:
    tests::test_c_api_hyphenated_uuid
    tests::test_c_api_simple_uuid
    tests::test_c_api_urn_uuid

OS : debian11

**Comment by ken-matsui** [comment]
@vidhyasasi Did you do `cargo build` before your test? Tests need to link its dynamic library.

**Comment by vidhyasasi** [comment]
@ken-matsui  Yes I did 
I followed the steps:
cargo build
cargo test
still the testing fails

**Comment by ken-matsui** [comment]
@vidhyasasi Can you send the actual error?

**Comment by vidhyasasi** [comment]
admin@ip-172-31-43-158:~/packages/uuid-v4-cli$ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.08s
     Running unittests src/lib.rs (target/debug/deps/uuid_v4_cli-191fc23883a20ea6)

running 3 tests
test tests::test_c_api_hyphenated_uuid ... FAILED
test tests::test_c_api_simple_uuid ... FAILED
test tests::test_c_api_urn_uuid ... FAILED

failures:

---- tests::test_c_api_hyphenated_uuid stdout ----
thread 'tests::test_c_api_hyphenated_uuid' panicked at 'Unexpected failure.
code-1
stderr=```"/usr/bin/ld: cannot find /home/admin/packages/uuid-v4-cli/target/debug/libuuid_v4_cli.dylib: No such file or directory\ncollect2: error: ld returned 1 exit status\n"```
command=`CFLAGS="-I/home/admin/packages/uuid-v4-cli/target/debug -L/home/admin/packages/uuid-v4-cli/target/debug -D_DEBUG -D_CRT_SECURE_NO_WARNINGS" LDFLAGS="/home/admin/packages/uuid-v4-cli/target/debug/libuuid_v4_cli.dylib" "cc" "/tmp/user/1000/inline-c-rs-FiYKg4.c" "-O1" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-Werror" "-I/home/admin/packages/uuid-v4-cli/target/debug" "-L/home/admin/packages/uuid-v4-cli/target/debug" "-D_DEBUG" "-D_CRT_SECURE_NO_WARNINGS" "-Wl,/home/admin/packages/uuid-v4-cli/target/debug/libuuid_v4_cli.dylib" "-o" "/tmp/user/1000/inline-c-rs-fr89aN"`
code=1
stdout=```""```
stderr=```"/usr/bin/ld: cannot find /home/admin/packages/uuid-v4-cli/target/debug/libuuid_v4_cli.dylib: No such file or directory\ncollect2: error: ld returned 1 exit status\n"```
', /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-1.0.8/src/assert.rs:124:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::test_c_api_simple_uuid stdout ----
thread 'tests::test_c_api_simple_uuid' panicked at 'Unexpected failure.
code-1
stderr=```"/usr/bin/ld: cannot find /home/admin/packages/uuid-v4-cli/target/debug/libuuid_v4_cli.dylib: No such file or directory\ncollect2: error: ld returned 1 exit status\n"```
command=`CFLAGS="-I/home/admin/packages/uuid-v4-cli/target/debug -L/home/admin/packages/uuid-v4-cli/target/debug -D_DEBUG -D_CRT_SECURE_NO_WARNINGS" LDFLAGS="/home/admin/packages/uuid-v4-cli/target/debug/libuuid_v4_cli.dylib" "cc" "/tmp/user/1000/inline-c-rs-Np0DLD.c" "-O1" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-Werror" "-I/home/admin/packages/uuid-v4-cli/target/debug" "-L/home/admin/packages/uuid-v4-cli/target/debug" "-D_DEBUG" "-D_CRT_SECURE_NO_WARNINGS" "-Wl,/home/admin/packages/uuid-v4-cli/target/debug/libuuid_v4_cli.dylib" "-o" "/tmp/user/1000/inline-c-rs-dz7Ew0"`
code=1
stdout=```""```
stderr=```"/usr/bin/ld: cannot find /home/admin/packages/uuid-v4-cli/target/debug/libuuid_v4_cli.dylib: No such file or directory\ncollect2: error: ld returned 1 exit status\n"```
', /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-1.0.8/src/assert.rs:124:9

---- tests::test_c_api_urn_uuid stdout ----
thread 'tests::test_c_api_urn_uuid' panicked at 'Unexpected failure.
code-1
stderr=```"/usr/bin/ld: cannot find /home/admin/packages/uuid-v4-cli/target/debug/libuuid_v4_cli.dylib: No such file or directory\ncollect2: error: ld returned 1 exit status\n"```
command=`CFLAGS="-I/home/admin/packages/uuid-v4-cli/target/debug -L/home/admin/packages/uuid-v4-cli/target/debug -D_DEBUG -D_CRT_SECURE_NO_WARNINGS" LDFLAGS="/home/admin/packages/uuid-v4-cli/target/debug/libuuid_v4_cli.dylib" "cc" "/tmp/user/1000/inline-c-rs-I6wBw8.c" "-O1" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-Werror" "-I/home/admin/packages/uuid-v4-cli/target/debug" "-L/home/admin/packages/uuid-v4-cli/target/debug" "-D_DEBUG" "-D_CRT_SECURE_NO_WARNINGS" "-Wl,/home/admin/packages/uuid-v4-cli/target/debug/libuuid_v4_cli.dylib" "-o" "/tmp/user/1000/inline-c-rs-KkjR5O"`
code=1
stdout=```""```
stderr=```"/usr/bin/ld: cannot find /home/admin/packages/uuid-v4-cli/target/debug/libuuid_v4_cli.dylib: No such file or directory\ncollect2: error: ld returned 1 exit status\n"```
', /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-1.0.8/src/assert.rs:124:9


failures:
    tests::test_c_api_hyphenated_uuid
    tests::test_c_api_simple_uuid
    tests::test_c_api_urn_uuid

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.21s

error: test failed, to rerun pass `--lib`

**Comment by ken-matsui** [comment]
@vidhyasasi Can you try the following and share the output?

```
rm -rf target
cargo build
cargo test
```
